class Pc15Error(RuntimeError): ...
class MissingCudaError(Pc15Error): ...
class UnknownGeneratorError(Pc15Error): ...
class InvalidParamsError(Pc15Error): ...
class BitstreamError(Pc15Error): ...
class ModelMissingError(Pc15Error): ...
class DeterminismViolationError(Pc15Error): ...
