[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pc15codec"
version = "15.0.0"
description = "Codec core (tiling, RD search, bitstream) for PC15 v15"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
