[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pc15wf"
version = "15.0.0"
description = "Workflow & idempotence helpers for PC15 v15"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
pc15-encode  = "pc15wf.cli.encode_batch:main"
pc15-decode  = "pc15wf.cli.decode:main"
pc15-metrics = "pc15wf.cli.metrics:main"
pc15-audit   = "pc15wf.cli.audit_generators:main"
